version: '3.3'

services:
  db:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql
    restart: always
    ports:
      - '5434:5432'

  redis:
    image: redis:3
    expose:
      - 6378

volumes:
  pg_data:
