import datetime
from typing import Optional

import pydantic


class AutoGeneratedFields(pydantic.BaseModel):
    class Config:
        abstract = True

    created_date: Optional[datetime.datetime]
    updated_date: Optional[datetime.datetime]
    deleted: Optional[bool] = False


class BaseSchema(pydantic.BaseModel):
    description: Optional[str]

    class Config:
        abstract = True
        orm_mode = True
