FROM python:3.9-alpine

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

RUN mkdir /app/staticfiles
RUN mkdir /app/media

RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev build-base libffi-dev

COPY ./requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./scripts/entrypoint.sh .
COPY . .

#ENTRYPOINT ["/app/entrypoint.sh"]
